<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Advanced Search' => 'Búsqueda avanzada',
    'All' => 'Todos',
    'Alternative Text' => 'Texto alternativo',
    'Browse' => 'Explorar',
    'Cancel' => 'Cancelar',
    'Category' => 'Categoría',
    'Click a file to view info.' => 'Haga click en un archivo para ver más información.',
    'Click {link} to create a folder to upload media' => 'Haga click acá: {link}, para crear un directorio y subir archivos',
    'Confirm delete {src_file_name} ?' => '¿Deseas borrar {src_file_name}?',
    'Copy' => 'Copiar',
    'Create Folder' => 'Crear directorio',
    'Created At' => 'Fecha de creación',
    'Delete' => 'Borrar',
    'Delete Permanently' => 'Borrar permanentemente',
    'Description' => 'Descripción',
    'Dimension' => 'Dimensión',
    'Edit' => 'Editar',
    'Enter or select tags...' => 'Ingrese o seleccione tags...',
    'Fail to create thumbnail.' => 'La creación de la thumbnail ha fallado',
    'File ID' => 'ID del archivo',
    'File Identifier' => 'Identificador del archivo',
    'File Name' => 'Nombre del archivo',
    'File dimension at most 2272 X 1704.' => 'Las dimensiones máximas del archivo son 2272 X 1704',
    'File not found.' => 'Archivo no encontrado',
    'Filename can only contain alphanumeric characters, underscores (_) and dashes (-).' => 'El nombre del archivo solo puede contener símbolos alfanuméricos, guiones bajos (_) o guiones (-)',
    'Folder ID' => 'ID del directorio',
    'Invalid file extension. Available file extension are {ext}' => 'La extensión del archivo es inválida. Las extensiones permitidas son {ext}',
    'Invalid file type. Available file types are {types}' => 'EL tipo de archivo es inválido. Los tipos permitidos son {types}',
    'Invalid folder location.' => 'Ubicación del directorio inválida',
    'Invalid value: {variable}' => 'Valor inválido: {variable}',
    'Library' => 'Librería',
    'Limit is {limit}MB' => 'El límite es {limit}MB',
    'Media Folder' => 'Directorio de archivos multimedia',
    'Media Gallery' => 'Galería multimedia',
    'Media Property' => 'Propiedades de archivo',
    'Mime Type' => 'Tipos de archivos',
    'Object Url' => 'Url del objeto',
    'Path' => 'Ruta',
    'Remove' => 'Remover',
    'Search' => 'Buscar',
    'Search by File Name, Title, Alternative Text or Description...' => 'Buscar por el Nombre del archivo, Titulo, Texto alternativo o Descripción',
    'Search by tag...' => 'Buscar por Tag',
    'Storage' => 'Almacenamiento',
    'Storage ID' => 'ID del almacenamiento',
    'Tag ID' => 'ID del Tag',
    'Tags' => 'Tags',
    'This {attribute} already been taken.' => 'Este {attribute} ya ha sido tomado',
    'Thumbnail File Name' => 'Nombre de la miniatura',
    'Title' => 'Título',
    'Update' => 'Actualizar',
    'Updated At' => 'Última actualización',
    'Upload New' => 'Subir nuevo',
    'Upload New Media' => 'Subir nuevo archivo multimedia',
    'Upload To' => 'Subir a',
    'Upload fail due to some reasons.' => 'Por alguna razón la subida a fallado',
    'Url' => '',
    'Use' => 'Usar',
    'Value' => 'Valor',
    'View' => 'Vista',
    'here' => 'aquí',
    'host' =>  '',
    'Update Folder' => 'Actualizar directorio'
];
