<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Advanced Search' => 'Erweiterte Suche',
    'All' => 'Alle',
    'Alternative Text' => 'alternativer Text',
    'Browse' => 'Durchsuchen',
    'Cancel' => 'Abbrechen',
    'Category' => 'Kategorie',
    'Click a file to view info.' => 'Klicken Sie auf eine Datei, um Informationen anzuzeigen.',
    'Click {link} to create a folder to upload media' => 'Klicken Sie auf {link}, um einen Ordner zum Hochladen von Medien zu erstellen.',
    'Confirm delete {src_file_name} ?' => 'Wollen Sie {src_file_name} wirklich löschen?',
    'Copy' => 'Kopieren',
    'Create Folder' => 'Ordner anlegen',
    'Created At' => 'Erstellt am',
    'Delete' => 'Löschen',
    'Delete Permanently' => 'Dauerhaft löschen',
    'Description' => 'Beschreibung',
    'Dimension' => 'Abmessungen',
    'Edit' => 'Bearbeiten',
    'Enter or select tags...' => 'Geben Sie Tags ein oder wählen Sie sie aus',
    'Fail to create thumbnail.' => 'Fehler beim Erstellen des Thumbnails',
    'File ID' => 'Datei ID',
    'File Identifier' => 'Datei Identifikator',
    'File Name' => 'Datei Name',
    'File dimension at most 2272 X 1704.' => 'Bildgröße höchstens 2272 X 1704.',
    'File not found.' => 'Datei nicht gefunden.',
    'File too large.' => 'Datei zu groß.',
    'Filename can only contain alphanumeric characters, underscores and dashes.' => 'Der Dateiname darf nur alphanumerische Zeichen und Bindestriche enthalten.',
    'Folder ID' => 'Ordner ID',
    'Invalid file extension. Available file extension are {ext}' => 'Ungültige Dateiendung. Verfügbare Dateierweiterung sind {ext}',
    'Invalid file type. Available file types are {types}' => 'Ungültiger Dateityp. Verfügbare Dateitypen sind {types}',
    'Invalid folder location.' => 'Ungültiger Ordner Pfad',
    'Invalid value: {variable}' => 'Ungültiger Wert: {variable}',
    'Library' => 'Bibliothek',
    'Limit is {limit}MB' => 'Limit ist {Limit} MB',
    'Media Folder' => 'Medienordner',
    'Media Gallery' => 'Medien Gallerie',
    'Media Property' => 'Medieneigenschaft',
    'Mime Type' => 'Mime Typ',
    'Object Url' => 'Objekt URL',
    'Path' => 'Pfad',
    'Remove' => 'Löschen',
    'Search' => 'Suche',
    'Search by File Name, Title, Alternative Text or Description...' => 'Suche nach Dateiname, Titel, Alternativem Text oder Beschreibung...',
    'Search by tag...' => 'Suche nach Tag',
    'Storage' => 'Speicher',
    'Storage ID' => 'Speicher ID',
    'Tag ID' => 'Tag ID',
    'Tags' => 'Tags',
    'This {attribute} already been taken.' => 'Das Attribut {Attribut} wurde bereits vergeben.',
    'Thumbnail File Name' => 'Dateiname des Thumbnails',
    'Title' => 'Titel',
    'Update' => 'Aktualisieren',
    'Update Folder' => 'Ordner aktualisieren',
    'Updated At' => 'Aktualisiert am',
    'Upload New' => 'Hochladen',
    'Upload New Media' => 'Laden Sie neue Medien hoch',
    'Upload To' => 'Etwas hochladen auf',
    'Upload fail due to some reasons.' => 'Der Upload ist aus bestimmten Gründen fehlgeschlagen.',
    'Url' => 'URL',
    'Use' => 'Benutzen',
    'Value' => 'Wert',
    'View' => 'Anschauen',
    'here' => 'Hier',
    'host' => 'Host',
];
