<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Advanced Search' => '',
    'All' => '',
    'Alternative Text' => '',
    'Browse' => '',
    'Cancel' => '',
    'Category' => '',
    'Click a file to view info.' => '',
    'Click {link} to create a folder to upload media' => '',
    'Confirm delete {src_file_name} ?' => '',
    'Copy' => '',
    'Create Folder' => '',
    'Created At' => '',
    'Delete' => '',
    'Delete Permanently' => '',
    'Description' => '',
    'Dimension' => '',
    'Edit' => '',
    'Enter or select tags...' => '',
    'Fail to create thumbnail.' => '',
    'File ID' => '',
    'File Identifier' => '',
    'File Name' => '',
    'File dimension at most 2272 X 1704.' => '',
    'File not found.' => '',
    'Filename can only contain alphanumeric characters, underscores and dashes.' => '',
    'Folder ID' => '',
    'Invalid file extension. Available file extension are {ext}' => '',
    'Invalid file type. Available file types are {types}' => '',
    'Invalid folder location.' => '',
    'Invalid value: {variable}' => '',
    'Library' => '',
    'Limit is {limit}MB' => '',
    'Media Folder' => '',
    'Media Gallery' => '',
    'Media Property' => '',
    'Mime Type' => '',
    'Object Url' => '',
    'Path' => '',
    'Remove' => '',
    'Search' => '',
    'Search by File Name, Title, Alternative Text or Description...' => '',
    'Search by tag...' => '',
    'Storage' => '',
    'Storage ID' => '',
    'Tag ID' => '',
    'Tags' => '',
    'This {attribute} already been taken.' => '',
    'Thumbnail File Name' => '',
    'Title' => '',
    'Update' => '',
    'Updated At' => '',
    'Upload New' => '',
    'Upload New Media' => '',
    'Upload To' => '',
    'Upload fail due to some reasons.' => '',
    'Url' => '',
    'Use' => '',
    'Value' => '',
    'View' => '',
    'here' => '',
    'host' => '',
];
